### ISSUE TITLE
Linhas Seletivas 

### ISSUE THREAD

**Issue by lucasromanomr** [prodest/api-ceturb#10]
Existe alguma previsão para adicionarem as linhas de ônibus seletivos? É algo que muita gente vem perguntando.

**Comment by vizeke** [comment]
Atualmente a Ceturb faz monitoramento apenas da frota do Transcol. 
Essa demanda já foi enviada a Ceturb.
Nossa API apenas busca os dados gerados pelo rastreamento e disponibiliza publicamente.

Para saber mais detalhes, favor entrar em contato diretamente com a Ceturb. Algumas opções são o "Fale Conosco" no próprio site da Ceturb ou pelo telefone: 08000 391517

**Comment by vizeke** [comment]
Caso a Ceturb implemente o rastreamento para Seletivos, automaticamente será disponibilizado pelo API.
