### ISSUE TITLE
Acesso a api

### ISSUE THREAD

**Issue by lucasromanomr** [prodest/api-ceturb#8]
Olá, gostaria de saber como que eu obtenho acesso a API, se tem previsão de liberar a api publicamente. Estou desenvolvendo um aplicativo e gostaria de ter acesso. Ou a API feita para a Prodest, ou a api feita pela Geocontrol (o que seria melhor ainda).

**Comment by mikaelhadler** [comment]
Pessoal, @alvarollmenezes @hoisel @vizeke temos alguma notícia? Seria muito bacana o serviço liberado.

**Comment by alvarollmenezes** [comment]
A API tem acesso público, uma documentação orientando a utilização será disponibilizada em breve.

Retorno aqui com o endereço para a documentação, assim que disponível.
